kind: pipeline
name: synbak

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: izdock/devtoolset-7-toolchain-centos7
  commands:
  - ./autogen.sh
  - ./configure
  - make release
  - cd release && alien synbak-*.noarch.rpm

- name: deploy
  image: appleboy/drone-scp:1
  settings:
    host: web01
    port: 22
    username:
      from_secret: WEB01_SFTP_USERNAME
    password:
      from_secret: WEB01_SFTP_PASSWORD
    strip_components: 1
    source: release/synbak-*.noarch.rpm
    target:
    - /var/www/virtual/repo.initzero.it/centos/7/RPMS/noarch
    - /var/www/virtual/repo.initzero.it/centos/8/RPMS/noarch
    - /var/www/virtual/repo.initzero.it/centos/9/RPMS/noarch

- name: updaterepo
  image: appleboy/drone-ssh
  settings:
    host: web01
    port: 22
    username:
      from_secret: WEB01_SFTP_USERNAME
    password:
      from_secret: WEB01_SFTP_PASSWORD
    script:
    - /var/www/virtual/repo.initzero.it/centos/7/updaterepo.sh
    - /var/www/virtual/repo.initzero.it/centos/8/updaterepo.sh
    - /var/www/virtual/repo.initzero.it/centos/9/updaterepo.sh
