#!/bin/sh
# Script for regenerating all autogenerated files.

#aclocal -I m4
#autoconf
#automake -a -c
#gettextize -c --no-changelog -f

autoreconf -f -i

cd po
for f in *.po; do
  if test -r "$f"; then
    lang=`echo $f | sed -e 's,\.po$,,'`
    msgfmt -c -o $lang.gmo $lang.po
  fi
done
cd ..

./configure
